# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release-Package Binaries

on:
  release:
    types:
      - published

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

  Package-NetSim-Linux:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSim
      archs: x64 arm arm64
      os: linux
        
  Package-NetSim-Windows:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSim
      archs: x64 arm arm64
      os: win

  Package-NetSim-MacOS-10-10:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSim
      archs: x64
      os: osx.10.10

  Package-NetSim-MacOS-11:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSim
      archs: x64
      os: osx.11.0
      
  Package-NetSim-Web-Linux:
    uses: ./.github/workflows/package-platform.yaml
    with:
       project: NetSimWeb
       archs: x64 arm arm64
       os: linux

  Package-NetSim-Web-Windows:
    uses: ./.github/workflows/package-platform.yaml
    with:
       project: NetSimWeb
       archs: x64 arm arm64
       os: win

  Package-NetSim-Web-MacOS-10-10:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSimWeb
      archs: x64
      os: osx.10.10

  Package-NetSim-Web-MacOS-11:
    uses: ./.github/workflows/package-platform.yaml
    with:
      project: NetSimWeb
      archs: x64
      os: osx.11.0

        
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
