# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release-Package Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      linux_arch: x64 arm arm64
      win_arch: x64 arm arm64
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package Linux
      run: |
        for arch in $linux_arch; 
        do
          dotnet publish -r linux-$arch -p:PublishSingleFile=true --self-contained true -o bin/linux/$arch -c release
          cp -r Assets/PAKs bin/linux/$arch
          mkdir bin/linux/$arch/NABUs
          cp -f Assets/Config/appsettings.linux.json bin/linux/$arch/appsettings.json
          zip -r nnae-linux-$arch.zip bin/linux/$arch
        done
    - name: Package Windows
      run: |
        for arch in $win_arch; 
        do
          dotnet publish -r win-$arch -p:PublishSingleFile=true --self-contained true -o bin/win/$arch -c release
          cp -r Assets/PAKs bin/win/$arch
          mkdir bin/win/$arch/NABUs
          cp -f Assets/Config/appsettings.win.json bin/win/$arch/appsettings.json
          zip -r nnae-win-$arch.zip bin/win/$arch
        done
    - name: Package MacOS
      run: |
        dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true -o bin/macos/x64 -c release
        cp -r Assets/PAKs bin/macos/x64
        mkdir bin/macos/x64/NABUs
        cp -f Assets/Config/appsettings.macos.json bin/macos/x64/appsettings.json
        zip -r nnae-macos-x64.zip bin/macos/x64

        dotnet publish -r osx.11.0-arm64 -p:PublishSingleFile=true --self-contained true -o bin/macos/arm64 -c release
        cp -r Assets/PAKs bin/macos/arm64
        mkdir bin/macos/arm64/NABUs
        cp -f Assets/Config/appsettings.macos.json bin/macos/arm64/appsettings.json
        zip -r nnae-macos-arm64.zip bin/macos/arm64
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
